### ISSUE TITLE
404 response to /regulator/{id}/ when not all ids could be mapped. 

### ISSUE THREAD

**Issue by alecKent** [Cannabis-Labeling-API/universal-cannabis-api#9]
I am curious about the logic for using 404 as the response if not all ids were able to be attached. 

404 is defined as ["The server has not found anything matching the Request-URI"](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html). 

If I am reading the docs correctly in the case that not all ids could be mapped the request URI `/regulator/{id}/` is valid and a matching resource was found, the issue exists within the array of ids to map.

Since the `/regulator/{id}/` transaction doesn't seem to follow ACID I think the request should return a 200 response code since it is possible that some ids were mapped successfully. 
Then it is on the caller to check if the `failures` array has data / exists at all. 

Thoughts on this?

**Comment by elibosley** [comment]
This is a really great point. I am happy to change to a 200 with a failure array.

**Comment by alecKent** [comment]
Nice. I think a 200 would result in the least amount of confusion. 
That way 404 can be reserved for when the requested resource is not found.

**Comment by danaspiegel** [comment]
#13

**Comment by danaspiegel** [comment]
Closing issue as this will be handled with issue #13
